function [BW_out,properties] = filterRegionspuzzle34(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 08-Sep-2024
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[22000, 25000]);

% Get properties.
properties = table(regionprops(BW_out, {'Area', 'Eccentricity'}))